name: Deploy production

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  release:
    runs-on: [self-hosted, linux, x64]

    env:
      DAGGER_ENGINE: container+podman://dagger-engine-v1.0.0-beta.13
      APPLICATION_NAME: ninescoding 
      REGISTRY: registry.ninescoding.com
      DEPLOY_IMAGE: registry.ninescoding.com/ninescoding:latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Checkout articles
        uses: actions/checkout@v5
        with:
          repository: ninesl/articles
          path: blog
          persist-credentials: false

      - name: Remove Git metadata
        run: rm -rf .git blog/.git

      - name: Build, publish, and deploy
        env:
          DEPLOY_VALUES: APP_IMAGE=${{ env.DEPLOY_IMAGE }}
        run: |
          "$HOME/.local/bin/dagger" -W github.com/ninesl/daggerer@master api call \
            release \
            --source=. \
            --registry="$REGISTRY" \
            --app-name="$APPLICATION_NAME" \
            --registry-username="$(<"$HOME/secrets/runner_registry_user")" \
            --registry-password="file://$HOME/secrets/runner_registry_token" \
            --ssh-key="file://$HOME/secrets/ssh_key" \
            --known-hosts="file://$HOME/secrets/known_hosts" \
            --ssh-target="debian@host.containers.internal" \
            --ssh-target-port=1337 \
            --ssh-key="file://$HOME/secrets/ssh_key" \
            --known-hosts="file://$HOME/secrets/known_hosts" \
            --deploy-directory="prod/$APPLICATION_NAME" \
            --deploy-container-runtime=podman \
            --deploy-directory=prod/$APPLICATION_NAME \
            --deploy-values="$DEPLOY_VALUES"
